### ISSUE TITLE
This is not a bug but a interface for me to communicate with Marcel

### ISSUE THREAD

**Issue by ashwarhussain** [MarcelRobeer/VisualNarrator#18]
Hello Marcel,

I was thinking if we can use Acceptance Criteria and add more information so that we can make it more comprehensive .. Any thoughts on this?

Raising this as a defect only to communicate with you.

regards,
Ashwar
ashwarhussain_live@hotmail.com

**Comment by MarcelRobeer** [comment]
Dear Ashwar,

I am currently not further developing Visual Narrator, but merely fixing bugs to keep it up-to-date for other tools in the GRIMM method of the RE Lab at Utrecht University. I would recommend to look at https://github.com/RELabUU/ if your suggestion is already part of their tools, and otherwise get into touch with them regarding this suggestion.

Marcel

**Comment by ashwarhussain** [comment]
Sure would do .. thanks Marcel. To put this on record I have enjoyed going thru the code of Visual Narrator. Great job, congratulations.

Regards,
Ashwar.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MarcelRobeer** [comment]
Thank you very much, Ashwar.
